version: '3.5'

services:
  postgres:
    container_name: iot-monitoring
    image: postgres
    environment:
      POSTGRES_USER: iot-monitoring
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6380:6379"
    volumes:
      - redis:/var/lib/redis/data

volumes:
  redis: