development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: iot_monitoring_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: iot_monitoring_production
